### PR TITLE
major tongseng refresh

### PR DESCRIPTION
**Pull request by mkalten**
Hey Fajran,
this is a comprehensive refresh for Tongseng,
most importantly including external device support in the GUI,
among various other improvements as shown in the changes.

If you are OK with it, I'd suggest to release a new version 0.5 with that!

### CODE REVIEW

**Comment by fajran** [comment]
Impressive!

Does it work/compile on El Capitan? I will create a new release from this.

Many thanks!

**Comment by mkalten** [comment]
Yes, I am working on it on Capitan, but it build as Universal binary for 10.6 and later.
I tested everything on an internal MBPro Trackpad, and an external Magic Mouse.

**Comment by mkalten** [comment]
Hey @fajran ... if you don't find the time to update TongSeng, you could also add me to your repository, so I can take care of that too ...
In any case, I am soon planning a TongSeng2 which will include both TUIO11 and TUIO2

**Comment by fajran** [comment]
Sorry I haven't had time to update Tongseng. I have added you to the collaborator list and feel free to make the update :-) thanks!

**Comment by mkalten** [comment]
ok, I'll take care of the rest ... and then upload the new release binary

**Pull request merged**
